apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: release-guard-backend
spec:
  template:
    spec:
      containers:
      - image: release-guard-backend # This is automatically substituted by Cloud Deploy / Skaffold
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: "1000m"
            memory: 1Gi
      timeoutSeconds: 600
